plugins:
  - jekyll-toc

url: stealthmate.github.io
baseurl: /saidai-deep-learning

toc:
  min_level: 1
  max_level: 3

theme: minima

collections:
  linux:
    output: True
    title: Linuxについて
    order: 0
  python:
    output: True
    title: Pythonについて
    order: 1

destination: docs

markdown: kramdown
mathjax: true
