plugins:
  - jekyll-toc
  - jekyll-feed

url: stealthmate.github.io
baseurl: /saidai-deep-learning

exclude:
- Gemfile
- Gemfile.lock
- jtomd
- excluded
- vendor

toc:
  min_level: 1
  max_level: 3

theme: minima

collections:
  linux:
    output: True
    title: Linuxについて
    order: 0
  python:
    output: True
    title: Pythonについて
    order: 1
  machine_learning:
    output: True
    title: 機械学習
    order: 2

destination: docs

feed:
  collections:
    - linux
    - python
    - machine_learning

markdown: kramdown
mathjax: true
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
