plugins:
  - jekyll-toc

url: stealthmate.github.io
baseurl: /saidai-deep-learning

toc:
  min_level: 1
  max_level: 3

theme: minima

collections:
  linux:
    output: True
    title: Linuxについて
    order: 0
  python:
    output: True
    title: Pythonについて
    order: 1
  machine_learning:
    output: True
    title: 機械学習
    order: 2

destination: docs

markdown: kramdown
mathjax: true
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
